### ISSUE TITLE
Water module

### ISSUE THREAD

**Issue by aisapatino** [TrackYourself/track-yourself#17] opened 2014-06-17 20:50 UTC
Track water intake
- [ ] backend
  - [ ] mongoose schema & model
  - [ ] express routes for REST API
  - [ ] unit tests
- [ ] angular module
  - [ ] controller(s)
  - [ ] template(s)
  - [ ] $resource service to connect to backend
  - [ ] unit tests
  - [ ] integration tests

**Comment by joshcanhelp** [comment] 2014-06-19 16:07
Dupe of #21

**Closed as completed by joshcanhelp** 2014-06-19 16:07 UTC
